
def compress_dxt1(data: bytes, width: int, height: int) -> bytes: ...
def compress_dxt3(data: bytes, width: int, height: int) -> bytes: ...
def compress_dxt5(data: bytes, width: int, height: int) -> bytes: ...
def decompress_dxt1(data: bytes, width: int, height: int) -> bytes: ...
def decompress_dxt3(data: bytes, width: int, height: int) -> bytes: ...
def decompress_dxt5(data: bytes, width: int, height: int) -> bytes: ...