
def compress_dxt1(data: bytes, width: int, height: int) -> bytes: ...

def compress_dxt3(data: bytes, width: int, height: int) -> bytes: ...
def decompress_dxt3(data: bytes, width: int, height: int) -> bytes: ...

def compress_dxt5(data: bytes, width: int, height: int) -> bytes: ...

def compress_bc1_intel(data: bytes, width: int, height: int) -> bytes: ...
def decompress_bc1_intel(data: bytes, width: int, height: int) -> bytes: ...
def compress_bc3_intel(data: bytes, width: int, height: int) -> bytes: ...
def decompress_bc3_intel(data: bytes, width: int, height: int) -> bytes: ...
def compress_bc4_intel(data: bytes, width: int, height: int) -> bytes: ...
def decompress_bc4_intel(data: bytes, width: int, height: int) -> bytes: ...
def compress_bc5_intel(data: bytes, width: int, height: int) -> bytes: ...
def decompress_bc5_intel(data: bytes, width: int, height: int) -> bytes: ...
def compress_bc6h_intel(data: bytes, width: int, height: int) -> bytes: ...
def compress_bc7_intel(data: bytes, width: int, height: int) -> bytes: ...