
[package]
name = "blockCompressor"
version = "0.1.0"
edition = "2021"

[lib]
name = "blockCompressor"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module", "abi3-py310"] }
rayon = "1.10"