def defilter_scanlines(raw: bytes, width: int, height: int, color_type: int, bit_depth: int) -> bytes: ...
def deinterlace_adam7(data: bytes, width: int, height: int, color_type: int, bit_depth: int) -> bytes: ...
